# -*- coding: utf-8 -*-
"""linebot_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DQnRO-xKtprr7Y6HQCeWcu5tg1t_lBE
"""

# 下列是於 cloud function 執行的 main.py（colab 無法直接使用）
# 可接收 line 輸入 22 縣市名稱 line bot 回傳天氣預報
import functions_framework
import json
import get_weather
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage

@functions_framework.http
def main(request):
    try:
        access_token = 'zd1+kPu9b4zjgJEanqzvLePmXzXZ4p8nuxBtuJjBrTFS8kZmk98/i1hg5cHp84p5lTlgVvV9hpdcnt5AYrPFhL2s9EFyK//rXSEUmlZG3UPcppFJf0ji5jfYkvbPK++jCdZ0q+DNmnCRa7fE/l/PDQdB04t89/1O/w1cDnyilFU='
        secret = '51ddae772af6b831da8eb84224254cc4'
        body = request.get_data(as_text=True)
        json_data = json.loads(body)
        line_bot_api = LineBotApi(access_token)
        handler = WebhookHandler(secret)
        signature = request.headers['X-Line-Signature']
        handler.handle(body, signature)
        # msg: 使用者輸入(的縣市名)
        msg = json_data['events'][0]['message']['text']
        # 將輸入縣市名稱傳入爬蟲模組取得天氣資訊
        msg = get_weather.weather(msg)
        tk = json_data['events'][0]['replyToken']
        # 使用 linebot api 將天氣資訊回傳給使用者
        line_bot_api.reply_message(tk,TextSendMessage(msg))
        # print 內容會顯示於 cloud function 的日誌上
        print(msg, tk)
    except:
        print(request.args)
    return 'OK'

"""# 新增區段"""

