# -*- coding: utf-8 -*-
"""linebot_requirement.txt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D399hvcWyYp_p--J7BEpm7jI7VfvZufM
"""

#  cloud function 上設定檔：requirement.txt
functions-framework==3.*
line-bot-sdk

